import { API_PATH } from './apiPath'

export const END_POINT = {
  LOGIN: `${API_PATH.AUTHENTICATE}/login`,
  LOGOUT: `${API_PATH.AUTHENTICATE}/logout`,
  PROPERTY_SELECTION: `${API_PATH.PROPERTY}/seikyuu`,
  SEIKYUU_ICHIRAN_INITIALIZE: `${API_PATH.SEIKYUU_ICHIRAN}/seikyuu-ichiran-initialize`,
  SEIKYUU_ICHIRAN_BILLING_INFORMATION: `${API_PATH.SEIKYUU_ICHIRAN}/seikyuu-ichiran`,
  SEIKYU_ICHIRAN_UPDATE_BILLING: `${API_PATH.SEIKYUU_ICHIRAN}/seikyuu-ichiran/update`,
  SEIKYU_ICHIRAN_CORNFIRM_BILLING: `${API_PATH.SEIKYUU_ICHIRAN}/seikyuu-ichiran/confirm`,
  EXPORT_SEIKYUU_INVOICE_CSV: `${API_PATH.SEIKYUU_ICHIRAN}/output-seikyuu`,
}